nodes:
  - name: edge1
    state_size: 11
    action_size: 4
    gamma: 0.95
    epsilon: 1.0
    epsilon_min: 0.01
    epsilon_decay: 0.995
    learning_rate: 0.001
    batch_size: 8
    stable_treshold: 0.001
    train_every: 10